spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

client:
  domain: ${CLIENT.DOMAIN}

cookie:
  domain: ${COOKIE.DOMAIN}
  secure: ${COOKIE.SECURE}