spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

client:
  domain: ${CLIENT_DOMAIN}

cookie:
  domain: ${COOKIE_DOMAIN}
  secure: ${COOKIE_SECURE}